development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: imsat
  username: root
  password: 

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  host: localhost
  encoding: utf8
  database: babrovka_imsat70
  username: root
  password: ks86ybdl!