production:
  solr:
    hostname: mysql2.locum.ru
    port: 3309
    log_level: WARNING
    database: babrovka_imsat70
    username: babrovka_imsat70
    password: Cr6f2mqQ
    

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    
